### ISSUE TITLE
client.im.file.create上传类型为stream时报错

### ISSUE THREAD

**Issue by ifuner** [larksuite/node-sdk#96] opened 2024-07-12 10:33 UTC
![image](https://github.com/user-attachments/assets/f0bbe3a5-b375-4201-81a7-1103cab9f003)

**Comment by ifuner** [comment] 2024-07-12 10:35
`
  const result = await client.im.file.create({
      data: {
       file_type: 'stream',
      file: fs.readFileSync(path.join(process.cwd(), 'package.json')),
      file_name: 'package.json ',
      }
    });
`

**Comment by ifuner** [comment] 2024-07-12 10:35
```javascript

  const result = await client.im.file.create({
      data: {
       file_type: 'stream',
      file: fs.readFileSync(path.join(process.cwd(), 'package.json')),
      file_name: 'package.json ',
      }
    });
```

**Comment by mazhe-nerd** [comment] 2024-07-15 02:51
Duplicate of: https://github.com/larksuite/node-sdk/issues/39

**Closed** 2024-07-23 03:54 UTC
Labels: duplicate
